title: Tiny PHP Framework
description: Tiny PHP Framework Documentation
theme: just-the-docs

url: https://ranaroussi.github.io/tiny

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/ranaroussi/tiny
